export enum EPortfolioType {
    Vlogs = "Vlogs",
    Ecommerce = "Ecommerce",
    Fashion = "Fashion",
    Branding = "Branding",
    UGC = "UGC",
    Music = "Music",
    BW = "B&W",
    Creators = "Creators",
    Beauty = "Beauty",
    Publications = "Publications",
    Sport = "Sport",
    Products = "Products",
    Swim = "Swim",
    Commercial = "Commercial",
    Lifestyle = "Lifestyle",
    Portraiture = "Portraiture",
    Film = "Film",
    Events = "Events",
    Mood = "Mood",
    Home = "Home",
}