const data = {
    AffiliatePlatform: [],
    AgeBracket: [],
    AmazonKickback: "0",
    AmazonOrderTotal: "",
    AmazonReferralFee: "",
    AmazonReviewBeautyWand: "",
    AmazonReviewCupper: "",
    AmazonReviewLink: "",
    AmazonReviewOil: "",
    AmazonReviewSoothingCream: "",
    AmazonReviewThePill: "",
    AmazonReviewWalkingPadPro: "",
    AmazonReviewWalkingPadStandard: "",
    AmazonStorefront: "",
    AmazonTax: "",
    AmountPaid: "0",
    AuditedJan2025: "true",
    BookingLink: "",
    ByCampaignsProposedPartners: [
        {
            ByCampaigns: {
                id: "16f0c01a-6178-48a3-aec5-53a75e7d24ac",
                Name: "REVO Whitelisting",
            },
        },
        {
            ByCampaigns: {
                id: "sdfffffffff",
                Name: "sdfffffffff",
            },
        },
    ],
    ByCityPartnerHQ: [
        {
            ByCity: {
                id: "489b2e65-3917-49f9-b019-4c948923a2a9",
                Name: "New York City",
            },
        },
    ],
    ByCountry: "",
    ByCountryPartners: [
        {
            ByCountry: {
                id: "a3cb0827-4814-4594-9360-be9d93503190",
                Name: "United States",
            },
        },
    ],
    ByProductPartnerHQ: [
        {
            ByProduct: {
                id: "5c44421d-1157-41c3-887d-21b28294e882",
                Name: "No Product Received",
            },
        },
    ],
    ByStatesPartnerHQ: [
        {
            ByStates: {
                id: "33d46c5f-9968-4cc7-b8d7-f8636c89f857",
                Name: "New York",
            },
        },
    ],
    ByTagsPartnerHQ: [
        {
            ByTags: {
                id: "b29a2ebf-2d03-4e4e-9757-0bcb6fa194dc",
                Name: "wellness",
            },
        },
        {
            ByTags: {
                id: "b29a2ebf-2d03-4e4e-9757-0bcb6fa194dc",
                Name: "wellness",
            }
        },
        {
            ByTags: {
                id: "b29a2ebf-2d03-4e4e-9757-0bcb6fa194dc",
                Name: "wellness",
            }
        },
        {
            ByTags: {
                id: "b29a2ebf-2d03-4e4e-9757-0bcb6fa194dc",
                Name: "wellness",
            }
        },
        {
            ByTags: {
                id: "b29a2ebf-2d03-4e4e-9757-0bcb6fa194dc",
                Name: "wellness",
            }
        },
    ],
    CampaignMonth: [],
    CaseStudies2: "",
    CaseStudies3: "",
    CaseStudiesPartnerHQ: [],
    Client: "",
    ClientStatus: "",
    ContentHQPartnerHQ: [],
    Contracts: [],
    ConversionsBundleCupper: 0,
    ConversionsCupper: 0,
    ConversionsMassageGun: 0,
    ConversionsOils: 0,
    ConversionsWalkingPad: 0,
    CurrentStatus: ["Gather Rates"],
    Deliverables: "",
    DestinationsPartners: [],
    Email: "contactyarirodriguez@gmail.com",
    EstimatedTaxes: "",
    Expense2024: "",
    FBAxLevanta: 0,
    Facebook: "",
    FacebookFollowing: 0,
    GoogleDriveFiles: "",
    HourlyRate: "",
    Instagram: "https://www.instagram.com/yarii.r",
    InstagramFollowing: 8344,
    JourneyStep: "Gather Rates",
    Lasteditedtime: "",
    LevantaAffiliateFee: "",
    LinkedIn: "",
    LinkedInConnections: 0,
    Linktree: "",
    MailingAddress: "",
    MediaKit: [],
    Medium: "",
    MonthSourced: "",
    Name: "Yari Rodriguez",
    Notes: "YT Creator (New Prospect) - Jam",
    Occupation: "",
    OneOffExpense: "",
    OpentoGifting: "",
    OpentoWhitelisting: "",
    Partner360Rate: "0",
    PartnerGallery: [],
    PartnerHQFacilities: [],
    PartnerHQPortfolios: [],
    PartnerHQProductionHQ: [],
    PartnerHQProfileCategory: [],
    PartnerHQServices: [],
    PartnerHQStakeholder: [
        {
            Stakeholder: {
                id: "4357e4b0-1bee-47d7-b7ed-3cd5bcc8ae4c",
                Name: "Angelica",
            },
        },
        {
            Stakeholder: {
                id: "4357e4b0-1bee-47d7-b7ed-3cd5bcc8ae4c",
                Name: "Angelica",
            },
        },
    ],
    PartnerIGRate: "0",
    PartnerPostViews: 0,
    PartnerTTRate: "0",
    PartnerUGCRate: "0",
    PartnerYTRate: "0",
    PaymentLink: "Not Found",
    PaypalFee: "",
    Phone: "",
    Pinterest: "",
    PinterestFollowing: 0,
    PlatformDeliverables: [],
    Platforms: [],
    Podcast: "",
    PreviousCollabExpense: "",
    ProfileImage: [
        "https://cdn.wolfstudios.ai/partner-HQ/attH8Ee6GBkAjkzmX.png",
    ],
    ProfileStatus: ["Prospect"],
    RECORDID: "",
    REVOAmazonOrderConfirmationNumber: "",
    REVOIGPost: "",
    REVOUGCArmyTTUsernamePW: "",
    REVOsCounteroffer: "",
    REVOsOffer: "",
    Receipts: [],
    RefusalReason: "",
    RemainingCredits: 0,
    SecondPaymentDate: "",
    ShippingExpense: "",
    ShippingFBAFeeGiftedPartners: "",
    Snapchat: "",
    SnapchatFollowing: 0,
    Soundcloud: "",
    SourcedFrom: [],
    Spotify: "",
    TTPost: "",
    Tiktok: "https://www.tiktok.com/@yari_rod",
    TiktokFollowing: 2520,
    TotalAudience: "11650",
    TotalContributedEngagementbyContent: "0",
    TotalExpense: "0",
    TotalProductCOGExpense: "0",
    TotalROI: "0",
    Twitch: "",
    UGCPaymentStatus: "Not started",
    UGCRetainerAmount: 0,
    UGCTikTokLink: "",
    Website: "",
    WhatsApp: "",
    X: "",
    XFollowing: 0,
    YTPost: "",
    Youtube: "https://www.youtube.com/@yarirodriguez./shorts",
    YoutubeFollowing: 786,
    id: "8b256796-3d59-4d18-b9a5-6b744dc4cb6a",
    isFeatured: false,
};
