export const defaultPartner = {
    name: '',
    email: '',
    phone: '',
    profile_image: '',
    website: '',
    state: '',
    tags: [],
    instagram: '',
    instagram_following: 0,
    tiktok: '',
    tiktok_following: 0,
    youtube: '',
    youtube_following: 0,
    x: '',
    x_following: 0,
    facebook: '',
    facebook_following: 0,
    pinterest: '',
    pinterest_following: 0,
    partner_IG_rate: 0,
    partner_TT_rate: 0,
    partner_YT_rate: 0,
    partner_UGC_rate: 0,
    partner_360_rate: 0,
    contract: '',
    products: '',
    contributed_campaigns: '',
    profile_category: 'MODEL',
    current_status: 'NOT_STARTED',
    profile_status: '',
    stakeholder: '',
    total_audience: 0,
    sourced_from: '',
};

export const defaultPartner1 = {
        name: "",
        email: "",
        currentStatus: [],
        journeyStep: "",
        profileStatus: [],
        notes: "",

        instagram: {
            url: '',
            following: 0
        },

        tiktok: {
            url: '',
            following: 0
        },

        youtube: {
            url: '',
            following: 0
        },

        hourlyRate: '',
        bookingLink: '',
        ageBracket: [],

        snapchat: {
            url: '',
            following: 0
        },

        linkedinConnections: 0,
        X:{
            url: '',
            following: 0
        },

        facebook: {
            url: '',
            following: 0
        },

        website: '',
        medium: '',
        soundcloud: '',
        spotify: '',
        opentoGifting: '',
        occupation: '',
        client: '',
        linkedin: '',
        mailingAddress: '',
        phone: '',

        pinterest: {
            url: '',
            following: 0
        },
        podcast: '',
        refusalReason: "",
        twitch: '',
        revoAmazonOrderConfirmationNumber: '',
        amazonReviewLink: '',
        amazonReviewCupper: '',
        amazonReviewThePill: '',
        amazonStorefront: '',
        deliverables: '',
        googleDriveFiles: '',
        revoIGPost: '',
        partnerIGRate: '',
        partnerTTRate: '',
        partnerYTRate: '',
        amountPaid: '',
        totalContributedEngagementByContent: '',
        totalAudience: '',
        platformDeliverables: [],
        platforms: [],
        previousCollabExpense: '',
        revoOffer: '',
        remainingCredits: 0,
        ttPost: '',
        totalROI: '',
        ugcPaymentStatus: '',
        ugcRetainerAmount: 0,
        ugcTikTokLink: '',
        revoUGCArmyTTUsernamePW: '',
        whatsApp: '',
        ytPost: '',
        partnerPostViews: 0,
        sourcedFrom: [],
        estimatedTaxes: '',
        fbaXLevanta: 0,
        shippingFBAFeeGiftedPartners: '',
        levantaAffiliateFee: '',
        paypalFee: '',
        shippingExpense: '',
        amazonReferralFee: '',
        amazonOrderTotal: '',
        amazonTax: '',
        amazonKickback: '',
        monthSourced: '',
        secondPaymentDate: '',
        clientStatus: '',
        linktree: '',
        partnerUGCRate: '',
        partner360Rate: '',
        revoCounteroffer: '',
        opentoWhitelisting: '',
        conversionsBundleCupper: 0,
        conversionsMassageGun: 0,
        conversionsCupper: 0,
        conversionsOils: 0,
        conversionsWalkingPad: 0,
        amazonReviewWalkingPadPro: '',
        amazonReviewWalkingPadStandard: '',
        amazonReviewOil: '',
        amazonReviewSoothingCream: '',
        amazonReviewBeautyWand: '',
        contracts: [],
        paymentLink: '',
        totalExpense: '0',
        totalProductCOGExpense: '0',
        affiliatePlatform: []
}