import { profileStatus, status } from './partner.constants';

export const defaultPartner = (data) => {
  const formattedValue = {
    id: data?.id || null,
    name: data?.Name || '',
    email: data?.Email || '',
    currentStatus:
      data?.CurrentStatus?.length > 0
        ? status.filter((i) => data.CurrentStatus.includes(i.value) || data.CurrentStatus.includes(i.label))
        : [],
    journeyStep: data?.JourneyStep || '',
    profileStatus:
      data?.ProfileStatus?.length > 0
        ? profileStatus.filter((i) => data.ProfileStatus.includes(i.value) || data.ProfileStatus.includes(i.label))
        : [],
    notes: data?.Notes || '',
    instagram: {
      url: data?.Instagram || '',
      following: data?.InstagramFollowing || 0,
    },
    tiktok: {
      url: data?.Tiktok || '',
      following: data?.TiktokFollowing || 0,
    },
    youtube: {
      url: data?.Youtube || '',
      following: data?.YoutubeFollowing || 0,
    },
    hourlyRate: data?.HourlyRate || '',
    bookingLink: data?.BookingLink || '',
    ageBracket: data?.AgeBracket?.length > 0 ? data?.AgeBracket.map((i) => ({ label: i, value: i })) : [],
    snapchat: {
      url: data?.Snapchat || '',
      following: data?.SnapchatFollowing || 0,
    },
    linkedinConnections: data?.LinkedInConnections || 0,
    X: {
      url: data?.X || '',
      following: data?.XFollowing || 0,
    },
    facebook: {
      url: data?.Facebook || '',
      following: data?.FacebookFollowing || 0,
    },
    website: data?.Website || '',
    medium: data?.Medium || '',
    soundcloud: data?.Soundcloud || '',
    spotify: data?.Spotify || '',
    opentoGifting: data?.OpentoGifting || '',
    occupation: data?.Occupation || '',
    client: data?.Client || '',
    linkedin: data?.LinkedIn || '',
    mailingAddress: data?.MailingAddress || '',
    phone: data?.Phone || '',
    pinterest: {
      url: data?.Pinterest || '',
      following: data?.PinterestFollowing || 0,
    },
    podcast: data?.Podcast || '',
    refusalReason: data?.RefusalReason || '',
    twitch: data?.Twitch || '',
    revoAmazonOrderConfirmationNumber: data?.REVOAmazonOrderConfirmationNumber || '',
    amazonReviewLink: data?.AmazonReviewLink || '',
    amazonReviewCupper: data?.AmazonReviewCupper || '',
    amazonReviewThePill: data?.AmazonReviewThePill || '',
    amazonStorefront: data?.AmazonStorefront || '',
    deliverables: data?.Deliverables || '',
    googleDriveFiles: data?.GoogleDriveFiles || '',
    revoIGPost: data?.REVOIGPost || '',
    partnerIGRate: data?.PartnerIGRate || '',
    partnerTTRate: data?.PartnerTTRate || '',
    partnerYTRate: data?.PartnerYTRate || '',
    amountPaid: data?.AmountPaid || '',
    totalContributedEngagementByContent: data?.TotalContributedEngagementbyContent || '0',
    totalAudience: data?.TotalAudience || '',
    platformDeliverables:
      data?.PlatformDeliverables?.length > 0 ? data?.PlatformDeliverables.map((i) => ({ label: i, value: i })) : [],
    platforms: data?.Platforms?.length > 0 ? data?.Platforms.map((i) => ({ label: i, value: i })) : [],
    previousCollabExpense: data?.PreviousCollabExpense || '',
    revoOffer: data?.REVOsOffer || '',
    remainingCredits: data?.RemainingCredits || 0,
    ttPost: data?.TTPost || '',
    totalROI: data?.TotalROI || '',
    ugcPaymentStatus: data?.UGCPaymentStatus || '',
    ugcRetainerAmount: data?.UGCRetainerAmount || 0,
    ugcTikTokLink: data?.UGCTikTokLink || '',
    revoUGCArmyTTUsernamePW: data?.REVOUGCArmyTTUsernamePW || '',
    whatsApp: data?.WhatsApp || '',
    ytPost: data?.YTPost || '',
    partnerPostViews: data?.PartnerPostViews || 0,
    sourcedFrom: data?.SourcedFrom?.length > 0 ? data?.SourcedFrom.map((i) => ({ label: i, value: i })) : [],
    estimatedTaxes: data?.EstimatedTaxes || '',
    fbaXLevanta: data?.FBAxLevanta || 0,
    shippingFBAFeeGiftedPartners: data?.ShippingFBAFeeGiftedPartners || '',
    levantaAffiliateFee: data?.LevantaAffiliateFee || '',
    paypalFee: data?.PaypalFee || '',
    shippingExpense: data?.ShippingExpense || '',
    amazonReferralFee: data?.AmazonReferralFee || '',
    amazonOrderTotal: data?.AmazonOrderTotal || '',
    amazonTax: data?.AmazonTax || '',
    amazonKickback: data?.AmazonKickback || '',
    monthSourced: data?.MonthSourced || '',
    secondPaymentDate: data?.SecondPaymentDate || '',
    clientStatus: data?.ClientStatus || '',
    linktree: data?.Linktree || '',
    partnerUGCRate: data?.PartnerUGCRate || '',
    partner360Rate: data?.Partner360Rate || '',
    revoCounteroffer: data?.REVOsCounteroffer || '',
    opentoWhitelisting: data?.OpentoWhitelisting || '',
    conversionsBundleCupper: data?.ConversionsBundleCupper || 0,
    conversionsMassageGun: data?.ConversionsMassageGun || 0,
    conversionsCupper: data?.ConversionsCupper || 0,
    conversionsOils: data?.ConversionsOils || 0,
    conversionsWalkingPad: data?.ConversionsWalkingPad || 0,
    amazonReviewWalkingPadPro: data?.AmazonReviewWalkingPadPro || '',
    amazonReviewWalkingPadStandard: data?.AmazonReviewWalkingPadStandard || '',
    amazonReviewOil: data?.AmazonReviewOil || '',
    amazonReviewSoothingCream: data?.AmazonReviewSoothingCream || '',
    amazonReviewBeautyWand: data?.AmazonReviewBeautyWand || '',
    contracts: data?.Contracts?.length > 0 ? data?.Contracts.map((i) => ({ label: i, value: i })) : [],
    paymentLink: data?.PaymentLink || '',
    totalExpense: data?.TotalExpense || '0',
    totalProductCOGExpense: data?.TotalProductCOGExpense || '0',
    affiliatePlatform:
      data?.AffiliatePlatform?.length > 0 ? data?.AffiliatePlatform.map((i) => ({ label: i, value: i })) : [],
    profileImage: data?.ProfileImage || [],
    mediaKit: data?.MediaKit || [],
    receipts: data?.Receipts || [],
  };

  return formattedValue;
};
