
export const defaultCampaign = {
  id: '',
  project_title: '',
  slug: '',
  category: '',
  video_url: '',
  hero_image: '',
  field_image: '',
  thumbnail: '',
  vertical_gallery_images: [],
  horizontal_gallery_images: [],
  date: '',
  short_description: '',
  full_description: '',
  state: '',
  partner_hq: '',
  user_id: '',
  created_by: '',
  updated_at: '',
};
