export const defaultCampaign = {
  name: '',
  thumbnail: '', // TODO: Add a thumbnail upload component
  stakeholder: '',
  status: 'PENDING',
  start_date: '',
  end_date: '',
  description: '',
  goal: '',
  partner_compensation: 0,
  partner_deliverables: '',
  contributed_partners: '',
  prospected_partners: '',
  content_HQ: '',
  content_guidelines: '',
  image_inspiration: '',
  video_inspiration: '',
  content_engagement: 0,
  product_expense: 0,
  partner_expense: 0,
  social_platforms: [{ platform: '', url: '' }], 
};
