export const defaultCampaign = {
  name: '',
  slug: '',
  campaign_group_id: '',
  campaign_group_name: '',
  guideline: null,
  campaign_image: null,
  content_engagement: 0,
  content_hq: null,
  note: null,
  stakeholder: null,
  campaign_status: 'UPCOMING',
  retail_partners: null,
  proposed_partners: null,
  live_partners: null,
  contributed_partners: null,
  image_gallery: [],
  video_gallery: [],
  budget: null,
  total_expense: null,
  campaign_ROI: null,
  start_date: null,
  end_date: null,
  description: '',
  spaces: null,
  product_expense: null,
};

export const defaultCampaignGroup = {
  name: '',
  description: '',
  campaigns: [],
};
