export const singleCampaignData = {
  title: 'Mary Ann',
  slug: 'mary-ann',
  description: 'Session with Mary Ann, shot by Combina in February 2018',
  model: 'Mary Ann',
  dp: 'Combina Key',
  projectLink: 'Link to project',
  category: 'Editorial',
  date: '2018-02-15',
  location: 'New York, USA',
  client: 'Vogue',
  tags: ['fashion', 'editorial', 'portraits'],
  videoLink: 'https://www.youtube.com/watch?v=example',
  gallery: ['https://picsum.photos/400/300?random=1', 'https://picsum.photos/400/300?random=2'],
  photographerBio: 'https://combina-key-portfolio.com',
  team: {
    stylist: 'Jane Doe',
    makeupArtist: 'Emily Smith',
    creativeDirector: 'John Carter',
  },
  engagementStats: {
    views: 12000,
    likes: 3400,
    shares: 450,
  },
  callToAction: 'Book a similar shoot with us!',
  testimonial: 'Loved working on this shoot! - Mary Ann',
  image: 'https://picsum.photos/300/200?random=1',
};

export const defaultCampaignData = {
  title: '',
  slug: '',
  description: '',
  model: '',
  dp: '',
  projectLink: '',
  category: '',
  date: '',
  location: '',
  client: '',
  tags: [],
  videoLink: '',
  gallery: [],
  photographerBio: '',
  team: {
    stylist: '',
    makeupArtist: '',
    creativeDirector: '',
  },
  engagementStats: {
    views: null,
    likes: null,
    shares: null,
  },
  callToAction: '',
  testimonial: '',
  image: '',
};
