
export const defaultSpace = {
    id: '',
    projectTitle: '',
    portfolioCategories: [],
    date: '',
    shortDescription: '',
    fullDescription: '',
    states: [],
    countries: [],
    partnerHQ: [],
  
    slug: '',
    video_url: '',
    hero_image: '',
    field_image: '',
    thumbnail: '',
    vertical_gallery_images: [],
    horizontal_gallery_images: [],
    user_id: '',
    created_by: '',
    updated_at: '',
  };

export const defaultSpace1 = {
    id: '',
    name: '',
    startingRatehr: '',
    bookingLink: '',
    type: [],
    spaceStyle: [],
    props: [],
    theme: [],
    availableLighting: [],
    adOns: [],
  
    cycWall:'',
    backdropSystem:'',
    features:[],
    minimumHourlyBooking: '',
    intro:'',
    aboutThisSpace:'',
    seeTheSpace:'',
    addToProject:'',
    recentCreatorsWhoBookedHere: '',
	  phoneNumber: '',
	  attendeeLimit: 15,
	  colorTone: '',
	  parkingInstructions: '',
	  lightingInformation: '',
	  soundInformation: '',
	  spaceAccess: '',
	  hostRules: '',
	  electrical: '',
	  permitDetails: '',
	  bedrooms: '',
	  bathrooms: '',
	  squareFootage: 600,
	  availableHours: "",
	  dateListed: "",

  //relations
  campaigns: [],
  cities:[],
  countries:[],
  states:[],
  tags:[],
  destinations:[],
  productionHQ:[],
  };