
export const defaultPortfolio = {
  id: '',
  projectTitle: '',
  slug: '',
  portfolioCategories: [],
  video_url: '',
  hero_image: '',
  field_image: '',
  thumbnail: '',
  vertical_gallery_images: [],
  horizontal_gallery_images: [],
  date: '',
  shortDescription: '',
  fullDescription: '',
  states: [],
  countries: [],
  partnerHQ: [],
  user_id: '',
  created_by: '',
  updated_at: '',
};
