export const defaultContent = (data) => {
  const defaultData = {
    name: data?.name || '',
    revoPinterest: data?.revoPinterest || '',
    pinAccountsUsed: data?.pinAccountsUsed || '',
    postQuality: data?.postQuality?.map((item) => item).join(', ') || '',
    googleDriveFiles: data?.googleDriveFiles || '',
    playbookLink: data?.playbookLink || '',
    upPromoteConversion: data?.upPromoteConversion || 0,
    assetStatus: data?.assetStatus || '',
    monthUploaded: data?.monthUploaded ? new Date(data?.monthUploaded) : null,
    revoInstagram: data?.revoInstagram || '',
    creatorStatus: data?.creatorStatus || '',
    partner: {
      IGLink: data?.partner?.IGLink || '',
      TikTokLink: data?.partner?.TikTokLink || '',
      TTShares: data?.partner?.TTShares || 0,
      TTSaves: data?.partner?.TTSaves || 0,
      TTViews: data?.partner?.TTViews || 0,
      TTLikes: data?.partner?.TTLikes || 0,
      TTComments: data?.partner?.TTComments || 0,
      YTLink: data?.partner?.YTLink || '',
    },
    IG: {
      SocialSetsUsed: data?.IG?.SocialSetsUsed || '',
      TotalComments: data?.IG?.TotalComments || 0,
      TotalLikes: data?.IG?.TotalLikes || 0,
      TotalShares: data?.IG?.TotalShares || 0,
      TotalViews: data?.IG?.TotalViews || 0,
    },
    YT: {
      ClubREVOTotalViews: data?.YT?.ClubREVOTotalViews || 0,
      PartnerTotalSaves: data?.YT?.PartnerTotalSaves || 0,
      PartnerTotalViews: data?.YT?.PartnerTotalViews || 0,
      PartnerTotalComments: data?.YT?.PartnerTotalComments || 0,
      PartnerTotalLikes: data?.YT?.PartnerTotalLikes || 0,
      REVOMADICTotalShares: data?.YT?.REVOMADICTotalShares || 0,
      REVOMADICTotalViews: data?.YT?.REVOMADICTotalViews || 0,
      REVOMADICTotalLikes: data?.YT?.REVOMADICTotalLikes || 0,
      REVOMADICTotalComments: data?.YT?.REVOMADICTotalComments || 0,
      ClubREVOTotalLikes: data?.YT?.ClubREVOTotalLikes || 0,
      AccountsUsed: data?.YT?.AccountsUsed || '',
    },
    Pinterest: {
      TotalPinClicks: data?.Pinterest?.TotalPinClicks || 0,
      TotalViews: data?.Pinterest?.TotalViews || 0,
    },
    REVO: {
      Twitter: data?.REVO?.Twitter || '',
      TTViews: data?.REVO?.TTViews || 0,
      TikTok: data?.REVO?.TikTok || '',
      Youtube: data?.REVO?.Youtube || '',
      ClubRevoYoutube: data?.REVO?.ClubRevoYoutube || '',
    },
    tikTokAccountsused: data?.tikTokAccountsused || '',
    TTDummyAccountsUsed: data?.TTDummyAccountsUsed.map((item) => item).join(', ') || '',
    postingStatus: data?.postingStatus || '',
    totalContributedEngagement: data?.totalContributedEngagement || '',
    campaigns: data?.campaigns || '',
    cities: data?.cities || '',
    products: data?.products || '',
    tags: data?.tags || '',
    stakeholders: data?.stakeholders || '',
    partners: data?.partners || '',
    retailPartners: data?.retailPartners || '',
  };

  return defaultData;
};
